#!/bin/bash

PASSED="PASSED"
FAILED="FAILED"
OUT_FILE="out"
DONE="./done"
FAILED_PROBLEMS=()

function usage {
    echo "usage: run problem.py"
}

if (( $# == 0 )); then
    usage
    exit 1
fi

if [[ "$1" == "-h" ]]; then
    usage
    exit 0
fi

FILE=$1

python3 $FILE > $OUT_FILE

cat $OUT_FILE

if grep -q $FAILED $OUT_FILE; then
    echo "$FILE FAILED"
    cat $OUT_FILE
    FAILED_PROBLEMS+=( $FILE )
else 
    echo "$FILE PASSED"
    git add $FILE
    git mv $FILE $DONE
fi

rm $OUT_FILE

